### ISSUE TITLE
demand mode were not work

### ISSUE THREAD

**Issue by imazes** [Cubix651/mtuchanger#3]
Good job,It was fabulous for me，but there are some que.
First :demand mode were not work by 5.0&5.1,was it a bug?
Second:is it possible to lock  LTE && wifi?

**Comment by Cubix651** [comment]
I wrote this app for my private purpose and I tested it only on my phones (Android 4.1 and older versions). Finally, I solved my problem with MTU at home in other way and I don't need MTUchanger right now. So I published the code on Google Code and recently I've moved it to Github to give other people possibility of installing this app or changing the source code and adjusting the app. It's plausible that there is a bug inside. Answering second question, WiFi and LTE interfaces are separate devices (as I suppose) so you should change interface from the dropdown list. Now, changing MTU of a few interfaces is unavailable.
